### ISSUE TITLE
List index out of range for placeholders

### ISSUE THREAD

**Issue by XapaJIaMnu** [hplt-project/OpusTrainer#20]
Whooops.
```
Traceback (most recent call last):
  File "/home/s1031254/anaconda3/bin/opustrainer-train", line 8, in <module>
    sys.exit(main())
  File "/home/s1031254/anaconda3/lib/python3.9/site-packages/opustrainer/trainer.py", line 725, in main
    for batch in state_tracker.run(trainer):
  File "/home/s1031254/anaconda3/lib/python3.9/site-packages/opustrainer/trainer.py", line 660, in run
    for batch in trainer.run(*args, **kwargs):
  File "/home/s1031254/anaconda3/lib/python3.9/site-packages/opustrainer/trainer.py", line 605, in run
    batch = [modifier(line.rstrip('\n')) + '\n' for line in batch]
  File "/home/s1031254/anaconda3/lib/python3.9/site-packages/opustrainer/trainer.py", line 605, in <listcomp>
    batch = [modifier(line.rstrip('\n')) + '\n' for line in batch]
  File "/home/s1031254/anaconda3/lib/python3.9/site-packages/opustrainer/modifiers/placeholders.py", line 304, in __call__
    if source[candidates[i][0]] == target[candidates[i][1]]:
IndexError: list index out of range
```
Not sure what triggers it, probably some malformed alignment pair. Triggered while training german-english wmt models.

**Comment by jelmervdl** [comment]
I just pushed an update [453146f](https://github.com/hplt-project/OpusTrainer/commit/453146fb32d42052f4b87f85a9798966cae14345) to main that should give you the exact line that caused this error, and adds checks in the placeholder code to make sure the alignment pairs are not going out of bounds.

Hopefully that helps you debug this a bit easier
